<!DOCTYPE html>
<html>

<head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1"> 
        <title>NYCGA</title> 
        <link rel="stylesheet" href="nycga.css" />
        <link rel="stylesheet" href="lib/jq/jquery.mobile-1.0rc2.min.css" />
        <script src="lib/jq/jquery-1.6.4.min.js"></script>
        <script src="lib/jq/jquery.mobile-1.0rc2.min.js"></script>
	<link rel="apple-touch-icon" href="apple-touch-icon.png"/>
</head>

<body>
